routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/home', 'HomeController@index')->name('home');



Auth::routes();


Route::get('/', 'PageController@index')->name('home');

Route::resource('courses', 'CourseController');

Route::resource('comments', 'CommentController');

Route::post('comments/store/{course}', 'CommentController@store')->name('comments.store');

Route::post('/reply/store/{comment}', 'CommentController@replyStore')->name('reply.store');
//
Route::delete('/reply/destroy/{reply}', 'CommentController@replyDestroy')->name('reply.destroy');


//Route::post('reply/{course}', 'CommentController@store')->name('comments.store');

//
//
//
//Route::post('/comment/store/{course}', 'CommentController@store')->name('comments.store');
//Route::post('/comment/destroy/{comment}', 'CommentController@store')->name('comments.destroy');
//
//Route::post('/reply/store/{comment}', 'CommentController@replyStore')->name('reply.store');
//
////Route::post('reply/destroy/{reply}', 'CommentController@replyDestroy')->name('reply.destroy');
//
//
////Route::post('reply/{course}', 'CommentController@store')->name('comments.store');

resources/views/courses/partials/_course_card.blade.php
<div class="col-md-4 pb-3">
    <div class="card  h-100">
        <h4 class="card-header">
            <a href="{{route('courses.show', $course->id)}}">{{$course->title}}
            </a>
        </h4>
        <div class="card-body">
            {!! nl2br($course->content) !!}
        </div>

        @if(Auth::user()!=null && Auth::user()->id==$course->user_id)
        <div class="card-footer">
            <a href="{{route('courses.edit', $course)}}" class="btn btn-outline-warning ">
                {{__('Edit')}}
            </a>
            <form method="post" action="{{route('courses.destroy', $course)}}" style="display: inline-block">
                @method('Delete')
                @csrf
                <button class="btn btn-outline-danger"
                        onclick="return confirm('{{__('Are you sure?')}}')"> {{__('Delete')}}</button>
            </form>

        </div>
            @endif
    </div>
</div>

resources/views/courses/partials/_replys.blade.php
<div class="container card">
    <h3 class="mt-2 ">{{__('Comments')}}</h3>
    <hr>

    <div class="card-body">
        @forelse($course->comments as $comment)
            <div class="card">
                <div class="card-header">
                    {{ '@'.$comment->user->name }} :-
                </div>

                <div class="card-body ml-4">
                    {{$comment->content}}
                </div>

            @if(Auth::user()!=null)
                <div class="card-footer">

{{--Reply on Comments Section--}}
                    <form method="post" action="{{route('reply.store',$comment->id)}}">
                        @csrf
                        <div class=" form-group">
                            <input type="text" name="content" class="form-control" placeholder='Type your reply here.'/>
                        </div>

                        <div class="form-group">
                            <input type="submit" class="btn btn-sm btn-outline-primary py-0" style="font-size: 0.8em;" value="Reply"/>
                        </div>
                    </form>



                    @if( Auth::user()->id==$comment->user_id)
{{--Delete a comment on course Section--}}
                    <form method="post" action="{{route('reply.destroy', $comment)}}">
                        @method('Delete')
                        @csrf
                        <button style="position: absolute; bottom: 28px; left: 80px; font-size: 0.8em;"
                                onclick="return confirm('{{__('Are you sure?')}}')"> {{__('Delete')}} <i class="fa fa-trash-o"></i></button>
                    </form>
                    @endif
                </div>
            @endif
            </div>

            <br>

            <div class="ml-5 card">
                @foreach($comment->replies as $reply)
                    <div class="card m-1 ">
                        <div class="card-header">
                            <span class="">{{ '@'.$reply->user->name }}, {{__('reply:- ')}}</span>
                        </div>

                        <div class="card-body">
                            <div class="ml-5">
                                {{$reply->content}}
                            </div>
                        </div>

                    @if(Auth::user()!=null)
                        <div class="card-footer">
                            <form method="post" action="{{route('reply.store', $comment->id )}}">
                                @csrf
                                <div class=" form-group">
                                    <input type="text" name="content" class="form-control"
                                           placeholder='Type your reply here.'/>
                                </div>
                                <div class="form-group">
                                    <input type="submit" class="btn btn-sm btn-outline-primary py-0"
                                           style="font-size: 0.8em;" value="Reply"/>

                                </div>
                            </form>


                            @if(Auth::user()->id==$reply->user_id)
{{--Delete a reply on comment Section--}}
                            <form method="post" action="{{route('reply.destroy', $reply)}}">
                                @method('Delete')
                                @csrf
                                <button id="delRep" style="position: absolute; bottom: 28px; left: 80px; font-size: 0.8em;" class="btn btn-sm btn-outline-danger py-0"
                                        onclick="return confirm('{{__('Are you sure?')}}')"> {{__('Delete')}}</button>
                            </form>
                            @endif
                        </div>
                        @endif
                    </div>

                @endforeach
            </div>
            <br>
        @empty
            <p style="color: gray;">{{__('No comments yet')}}</p>
        @endforelse

    </div>

</div>