routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/home', 'HomeController@index')->name('home');



Auth::routes();


Route::get('/', 'PageController@index')->name('home');

Route::resource('courses', 'CourseController');

Route::resource('comments', 'CommentController');

Route::post('comments/store/{course}', 'CommentController@store')->name('comments.store');

Route::post('/reply/store/{comment}', 'CommentController@replyStore')->name('reply.store');
//
Route::delete('/reply/destroy/{reply}', 'CommentController@replyDestroy')->name('reply.destroy');


//Route::post('reply/{course}', 'CommentController@store')->name('comments.store');

//
//
//
//Route::post('/comment/store/{course}', 'CommentController@store')->name('comments.store');
//Route::post('/comment/destroy/{comment}', 'CommentController@store')->name('comments.destroy');
//
//Route::post('/reply/store/{comment}', 'CommentController@replyStore')->name('reply.store');
//
////Route::post('reply/destroy/{reply}', 'CommentController@replyDestroy')->name('reply.destroy');
//
//
////Route::post('reply/{course}', 'CommentController@store')->name('comments.store');

resources/views/courses/create.blade.php
@extends('layouts.app')

@section('title', __('Create course'))

@section('content')

    <h2>{{__('Create course')}}</h2>
    <form action="{{route('courses.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label class="col-form-label" for="title">Course title: </label>
            <input type="text" class="form-control" name="title" placeholder="Ex:HTML" id="title">
        </div>

        <div class="form-group">
            <label class="col-form-label" for="content">Course description: </label>
            <textarea class="form-control"
                      name="content" id="content"
                      cols="30"
                      rows="10"
                      placeholder="Create a HTML web page...">
        @isset($course){{$course->content}}@endisset
    </textarea>
        </div>

        <div class="form-group ">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>

    </form>

@endsection

resources/views/courses/edit.blade.php
@extends('layouts.app')

@section('title', __('Edit course'))

@section('content')

    <h2>{{__('Edit course')}} : {{$course->title}}</h2>
    <form action="{{route('courses.update', $course)}}" method="post">
        @csrf

        @method('Patch')
        <div class="form-group">
            <label class="col-form-label" for="title">Course title: </label>
            <input type="text"
                   class="form-control"
                   name="title" placeholder="Ex:HTML"
                   id="title"
                   @isset($course) value="{{$course->title}}" @endisset>
        </div>

        <div class="form-group">
            <label class="col-form-label" for="content">Course description: </label>
            <textarea class="form-control"
                      name="content" id="content"
                      cols="30"
                      rows="10"
                      placeholder="Create a HTML web page...">
        @isset($course){{$course->content}}@endisset
    </textarea>
        </div>

        <div class="form-group ">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>

    </form>

@endsection

resources/views/courses/index.blade.php
@extends('layouts.app')

@section('title', __('Home page'))
<style>
    #addCourse{
        position: absolute;
        top: 80px;
        right: 190px;
    }
</style>
@section('content')

    <div class="container text-right ">
        <h3 class="text-left text-primary active mb-3">{{__('The Courses')}}</h3>
        <hr class="my-4">
        <a href="{{route('courses.create')}}" id="addCourse" class=" btn btn-lg btn-outline-primary mb-3 ">{{__('Add New Course')}}</a>
    </div>

    <div class="row">
        @forelse($courses as $course)
            @include('courses.partials._course_card')
        @empty
            {{__('No courses yet')}}
        @endforelse
    </div>
@endsection

resources/views/courses/show.blade.php
@extends('layouts.app')

@section('title', $course->title)

@section('content')


    {{--Course Info--}}
    <div class="card">

        <h4 class="card-header">
            {!! nl2br($course->title)!!}
        </h4>

        <div class="card-body">
            {!! nl2br($course->content) !!}
        </div>


        {{--Author Info--}}
        <div class="card-footer">
            <div><b>{{__('Author')}} : </b> {{$course->user->name}}</div>
            <div><b>{{__('Created at')}} :</b> {{$course->created_at}}</div>
            <div><b>{{__('Updated at')}} :</b> {{$course->updated_at}}</div>
        </div>

    </div>


    {{--Comments Section--}}
    <div class="mt-5">
        @include('courses.partials._replys', ['comments' => $course->comments, 'course_id' => $course->id])
    </div>



    {{--Writing Comment Section--}}
    <div class="card  mt-5">
        @auth
            <h5 class="card-header bg-secondary text-gray">{{__('Type your comment here')}}</h5>

            <div class="card-body">
                <form method="post" action="{{route('comments.store', $course->id)}}">
                    @csrf
                    <div class="form-group">

                        <label for="content">
                            {{__('Content')}}
                        </label>

                        <textarea class="form-control"
                                  placeholder="{{__('Type your comment here')}}"
                                  name="content"
                                  cols="30" rows="10">
                        </textarea>

                    </div>

                    <div class="form-group">
                        <input class="btn btn-outline-success  py-0" value="Save" type="submit"/>
                    </div>
                </form>
            </div>
        @else
            <a class="m-1" href="{{route('login')}}">{{__('Log in to comment')}}</a>
        @endauth
    </div>
@endsection